// Excerpt from functions/src/index.ts
// Lines 1262-1403: Thumbnail handling in onMediaFileFinalize Cloud Function

// This function is triggered when files are finalized in Firebase Storage
// It detects when thumbnails are generated by the storage-resize-images extension
// and updates Firestore with thumbnail paths and ready flags

// Handle extension-generated thumbnails - update Firestore when ready
// Firebase Extensions create thumbnails in format: .../thumbnails/filename_{size}.ext
// Sizes: 400x400, 800x800, 1200x1200
if (name.includes('/thumbnails/')) {
  console.log('🖼️ [THUMBNAIL FINALIZE] Thumbnail finalized:', name);
  
  // Extract thumbnail size and parent directory
  let thumbnailSize: 'small' | 'medium' | 'large' | null = null;
  if (name.includes('_400x400.')) {
    thumbnailSize = 'small';
  } else if (name.includes('_800x800.')) {
    thumbnailSize = 'medium';
  } else if (name.includes('_1200x1200.')) {
    thumbnailSize = 'large';
  }
  
  if (!thumbnailSize) {
    console.log('⏭️ Skipping thumbnail with unknown size:', name);
    return;
  }
  
  // Extract parent directory (media/{userId}/{batchId})
  // Thumbnail path: media/{userId}/{batchId}/thumbnails/{filename}_{size}.ext
  // Parent dir: media/{userId}/{batchId}
  const thumbnailsIndex = name.indexOf('/thumbnails/');
  if (thumbnailsIndex === -1) {
    console.log('⏭️ Skipping thumbnail with invalid path:', name);
    return;
  }
  
  const parentDir = name.substring(0, thumbnailsIndex);
  console.log('🔍 [THUMBNAIL] Parent directory:', parentDir);
  
  // Find the media document by storageFolder (with fallback to filePath)
  // Try multiple path formats to handle edge cases
  const searchFolderWithSlash = parentDir.endsWith('/') ? parentDir : `${parentDir}/`;
  const searchFolderWithoutSlash = parentDir.endsWith('/') ? parentDir.slice(0, -1) : parentDir;
  
  let mediaSnapshot = await db.collection('media')
    .where('storageFolder', '==', searchFolderWithSlash)
    .limit(1)
    .get();
  
  // Try without trailing slash if first attempt failed
  if (mediaSnapshot.empty) {
    mediaSnapshot = await db.collection('media')
      .where('storageFolder', '==', searchFolderWithoutSlash)
      .limit(1)
      .get();
  }
  
  // Fallback: If no match by storageFolder, try to find by filePath pattern
  // Extract the original filename from thumbnail path (remove _size suffix)
  if (mediaSnapshot.empty) {
    console.log('⚠️ [THUMBNAIL] No match by storageFolder, trying fallback query...');
    
    // Extract original filename from thumbnail: thumbnails/image_800x800.jpg -> image.jpg
    const thumbnailFileName = name.substring(name.lastIndexOf('/') + 1);
    const originalFileName = thumbnailFileName
      .replace(/_400x400\./, '.')
      .replace(/_800x800\./, '.')
      .replace(/_1200x1200\./, '.');
    
    // Try to find by filePath pattern (any file in the same folder)
    const filePathPattern = `${parentDir}/${originalFileName}`;
    mediaSnapshot = await db.collection('media')
      .where('filePath', '==', filePathPattern)
      .limit(1)
      .get();
    
    // If still no match, try to find ANY document in the same folder
    if (mediaSnapshot.empty) {
      console.log('⚠️ [THUMBNAIL] No match by filePath, trying any document in folder...');
      // Get recent documents and filter by folder (fallback for when query fails)
      const allDocs = await db.collection('media')
        .orderBy('createdAt', 'desc')
        .limit(200)
        .get();
      
      const matchingDoc = allDocs.docs.find(doc => {
        const docFolder = doc.data()?.storageFolder || '';
        const docFilePath = doc.data()?.filePath || '';
        const normalizedDocFolder = docFolder.endsWith('/') ? docFolder : `${docFolder}/`;
        const normalizedParentDir = parentDir.endsWith('/') ? parentDir : `${parentDir}/`;
        return normalizedDocFolder === normalizedParentDir || 
               docFolder === parentDir ||
               docFilePath.startsWith(parentDir) ||
               docFilePath.includes(parentDir);
      });
      
      if (matchingDoc) {
        mediaSnapshot = { docs: [matchingDoc], empty: false } as any;
        console.log('✅ [THUMBNAIL] Found document using fallback filter');
      }
    }
  }
  
  if (mediaSnapshot.empty) {
    console.error('❌ [THUMBNAIL] No media document found for thumbnail after all attempts:', name);
    return;
  }
  
  const mediaRef = mediaSnapshot.docs[0].ref;
  const mediaId = mediaRef.id;
  console.log('✅ [THUMBNAIL] Found media document:', mediaId);
  
  // Update Firestore with thumbnail status
  try {
    const thumbnailUpdate: any = {
      [`thumbnails.${thumbnailSize}Ready`]: true,
      [`thumbnails.${thumbnailSize}Path`]: name,
      [`thumbnails.updatedAt`]: FieldValue.serverTimestamp()
    };
    
    await mediaRef.set(thumbnailUpdate, { merge: true });
    console.log(`✅ [THUMBNAIL] Updated media document ${mediaId} with ${thumbnailSize} thumbnail ready:`, name);
  } catch (error) {
    console.error(`❌ [THUMBNAIL] Failed to update Firestore for ${mediaId}:`, error);
  }
  
  return; // Don't process thumbnails further
}

// Key Points:
// 1. Detects thumbnails by checking if path includes '/thumbnails/'
// 2. Extracts size from filename (_400x400, _800x800, _1200x1200)
// 3. Finds corresponding media document in Firestore
// 4. Updates Firestore with:
//    - thumbnails.smallReady / mediumReady / largeReady (boolean)
//    - thumbnails.smallPath / mediumPath / largePath (string)
//    - thumbnails.updatedAt (timestamp)
// 5. MediaCard.tsx reads these flags to determine which thumbnail to load

