// File generated by FlutterFire CLI — replace with your project via:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Until then, fill in the Android/iOS values from the Firebase console
// (Project settings → Your apps) or paste from google-services.json / GoogleService-Info.plist.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'momsfitnessmojo-dev',
    authDomain: 'momsfitnessmojo-dev.firebaseapp.com',
    storageBucket: 'momsfitnessmojo-dev.firebasestorage.app',
    measurementId: 'G-REPLACE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh4c6y4NElJoQTLNAl_necnrmRQMBY9s0',
    appId: '1:313384637691:android:862cd595cbfcc262634c5e',
    messagingSenderId: '313384637691',
    projectId: 'momsfitnessmojo-65d00',
    storageBucket: 'momsfitnessmojo-65d00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY8E5W-2N7TRiRNn-WQ6eXa21a-qabiSE',
    appId: '1:313384637691:ios:c8cdf387f3c5ea43634c5e',
    messagingSenderId: '313384637691',
    projectId: 'momsfitnessmojo-65d00',
    storageBucket: 'momsfitnessmojo-65d00.firebasestorage.app',
    iosBundleId: 'com.momfitnessmojo.mojoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'momsfitnessmojo-dev',
    storageBucket: 'momsfitnessmojo-dev.firebasestorage.app',
    iosBundleId: 'com.momfitnessmojo.mojoMobile',
  );
}

bool get firebaseOptionsConfigured {
  return !DefaultFirebaseOptions.android.apiKey.contains('REPLACE_ME');
}